//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MonitoringModel", "FK_Calibration_Ids", "Ids", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Id), "Calibration", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Calibration), true)]
[assembly: EdmRelationshipAttribute("MonitoringModel", "FK_HistoricalData_Ids", "Ids", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Id), "HistoricalData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.HistoricalData), true)]
[assembly: EdmRelationshipAttribute("MonitoringModel", "FK_ReadIntervals_Ids", "Ids", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Id), "ReadIntervals", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.ReadInterval), true)]

#endregion

namespace DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MonitoringEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MonitoringEntities object using the connection string found in the 'MonitoringEntities' section of the application configuration file.
        /// </summary>
        public MonitoringEntities() : base("name=MonitoringEntities", "MonitoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MonitoringEntities object.
        /// </summary>
        public MonitoringEntities(string connectionString) : base(connectionString, "MonitoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MonitoringEntities object.
        /// </summary>
        public MonitoringEntities(EntityConnection connection) : base(connection, "MonitoringEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Calibration> Calibrations
        {
            get
            {
                if ((_Calibrations == null))
                {
                    _Calibrations = base.CreateObjectSet<Calibration>("Calibrations");
                }
                return _Calibrations;
            }
        }
        private ObjectSet<Calibration> _Calibrations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HistoricalData> HistoricalDatas
        {
            get
            {
                if ((_HistoricalDatas == null))
                {
                    _HistoricalDatas = base.CreateObjectSet<HistoricalData>("HistoricalDatas");
                }
                return _HistoricalDatas;
            }
        }
        private ObjectSet<HistoricalData> _HistoricalDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Id> Ids
        {
            get
            {
                if ((_Ids == null))
                {
                    _Ids = base.CreateObjectSet<Id>("Ids");
                }
                return _Ids;
            }
        }
        private ObjectSet<Id> _Ids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReadInterval> ReadIntervals
        {
            get
            {
                if ((_ReadIntervals == null))
                {
                    _ReadIntervals = base.CreateObjectSet<ReadInterval>("ReadIntervals");
                }
                return _ReadIntervals;
            }
        }
        private ObjectSet<ReadInterval> _ReadIntervals;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calibrations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalibrations(Calibration calibration)
        {
            base.AddObject("Calibrations", calibration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HistoricalDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistoricalDatas(HistoricalData historicalData)
        {
            base.AddObject("HistoricalDatas", historicalData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIds(Id id)
        {
            base.AddObject("Ids", id);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReadIntervals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReadIntervals(ReadInterval readInterval)
        {
            base.AddObject("ReadIntervals", readInterval);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MonitoringModel", Name="Calibration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Calibration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Calibration object.
        /// </summary>
        /// <param name="calibrationId">Initial value of the CalibrationId property.</param>
        /// <param name="idId">Initial value of the IdId property.</param>
        /// <param name="calibrationOperation">Initial value of the CalibrationOperation property.</param>
        /// <param name="calibrationValue">Initial value of the CalibrationValue property.</param>
        /// <param name="isEnabled">Initial value of the IsEnabled property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="timestamp">Initial value of the timestamp property.</param>
        public static Calibration CreateCalibration(global::System.Int32 calibrationId, global::System.Int32 idId, global::System.Int32 calibrationOperation, global::System.Double calibrationValue, global::System.Boolean isEnabled, global::System.DateTime date, global::System.Byte[] timestamp)
        {
            Calibration calibration = new Calibration();
            calibration.CalibrationId = calibrationId;
            calibration.IdId = idId;
            calibration.CalibrationOperation = calibrationOperation;
            calibration.CalibrationValue = calibrationValue;
            calibration.IsEnabled = isEnabled;
            calibration.Date = date;
            calibration.timestamp = timestamp;
            return calibration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CalibrationId
        {
            get
            {
                return _CalibrationId;
            }
            set
            {
                if (_CalibrationId != value)
                {
                    OnCalibrationIdChanging(value);
                    ReportPropertyChanging("CalibrationId");
                    _CalibrationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CalibrationId");
                    OnCalibrationIdChanged();
                }
            }
        }
        private global::System.Int32 _CalibrationId;
        partial void OnCalibrationIdChanging(global::System.Int32 value);
        partial void OnCalibrationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdId
        {
            get
            {
                return _IdId;
            }
            set
            {
                OnIdIdChanging(value);
                ReportPropertyChanging("IdId");
                _IdId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdId");
                OnIdIdChanged();
            }
        }
        private global::System.Int32 _IdId;
        partial void OnIdIdChanging(global::System.Int32 value);
        partial void OnIdIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CalibrationOperation
        {
            get
            {
                return _CalibrationOperation;
            }
            set
            {
                OnCalibrationOperationChanging(value);
                ReportPropertyChanging("CalibrationOperation");
                _CalibrationOperation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CalibrationOperation");
                OnCalibrationOperationChanged();
            }
        }
        private global::System.Int32 _CalibrationOperation;
        partial void OnCalibrationOperationChanging(global::System.Int32 value);
        partial void OnCalibrationOperationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CalibrationValue
        {
            get
            {
                return _CalibrationValue;
            }
            set
            {
                OnCalibrationValueChanging(value);
                ReportPropertyChanging("CalibrationValue");
                _CalibrationValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CalibrationValue");
                OnCalibrationValueChanged();
            }
        }
        private global::System.Double _CalibrationValue;
        partial void OnCalibrationValueChanging(global::System.Double value);
        partial void OnCalibrationValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnabled
        {
            get
            {
                return _IsEnabled;
            }
            set
            {
                OnIsEnabledChanging(value);
                ReportPropertyChanging("IsEnabled");
                _IsEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnabled");
                OnIsEnabledChanged();
            }
        }
        private global::System.Boolean _IsEnabled;
        partial void OnIsEnabledChanging(global::System.Boolean value);
        partial void OnIsEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_timestamp);
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.Byte[] _timestamp;
        partial void OntimestampChanging(global::System.Byte[] value);
        partial void OntimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_Calibration_Ids", "Ids")]
        public Id Id
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_Calibration_Ids", "Ids").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_Calibration_Ids", "Ids").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Id> IdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_Calibration_Ids", "Ids");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Id>("MonitoringModel.FK_Calibration_Ids", "Ids", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MonitoringModel", Name="HistoricalData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HistoricalData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HistoricalData object.
        /// </summary>
        /// <param name="histocalDataId">Initial value of the HistocalDataId property.</param>
        /// <param name="idId">Initial value of the IdId property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static HistoricalData CreateHistoricalData(global::System.Int32 histocalDataId, global::System.Int32 idId, global::System.Double value, global::System.DateTime date)
        {
            HistoricalData historicalData = new HistoricalData();
            historicalData.HistocalDataId = histocalDataId;
            historicalData.IdId = idId;
            historicalData.Value = value;
            historicalData.Date = date;
            return historicalData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HistocalDataId
        {
            get
            {
                return _HistocalDataId;
            }
            set
            {
                if (_HistocalDataId != value)
                {
                    OnHistocalDataIdChanging(value);
                    ReportPropertyChanging("HistocalDataId");
                    _HistocalDataId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HistocalDataId");
                    OnHistocalDataIdChanged();
                }
            }
        }
        private global::System.Int32 _HistocalDataId;
        partial void OnHistocalDataIdChanging(global::System.Int32 value);
        partial void OnHistocalDataIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdId
        {
            get
            {
                return _IdId;
            }
            set
            {
                OnIdIdChanging(value);
                ReportPropertyChanging("IdId");
                _IdId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdId");
                OnIdIdChanged();
            }
        }
        private global::System.Int32 _IdId;
        partial void OnIdIdChanging(global::System.Int32 value);
        partial void OnIdIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Double _Value;
        partial void OnValueChanging(global::System.Double value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_timestamp);
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.Byte[] _timestamp;
        partial void OntimestampChanging(global::System.Byte[] value);
        partial void OntimestampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_HistoricalData_Ids", "Ids")]
        public Id Id
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_HistoricalData_Ids", "Ids").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_HistoricalData_Ids", "Ids").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Id> IdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_HistoricalData_Ids", "Ids");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Id>("MonitoringModel.FK_HistoricalData_Ids", "Ids", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MonitoringModel", Name="Id")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Id : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Id object.
        /// </summary>
        /// <param name="id1">Initial value of the Id1 property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="moduleNumber">Initial value of the ModuleNumber property.</param>
        /// <param name="moduleType">Initial value of the ModuleType property.</param>
        /// <param name="pDIN">Initial value of the PDIN property.</param>
        public static Id CreateId(global::System.Int32 id1, global::System.String iP, global::System.Int32 moduleNumber, global::System.Int32 moduleType, global::System.Int32 pDIN)
        {
            Id id = new Id();
            id.Id1 = id1;
            id.IP = iP;
            id.ModuleNumber = moduleNumber;
            id.ModuleType = moduleType;
            id.PDIN = pDIN;
            return id;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id1
        {
            get
            {
                return _Id1;
            }
            set
            {
                if (_Id1 != value)
                {
                    OnId1Changing(value);
                    ReportPropertyChanging("Id1");
                    _Id1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id1");
                    OnId1Changed();
                }
            }
        }
        private global::System.Int32 _Id1;
        partial void OnId1Changing(global::System.Int32 value);
        partial void OnId1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleNumber
        {
            get
            {
                return _ModuleNumber;
            }
            set
            {
                OnModuleNumberChanging(value);
                ReportPropertyChanging("ModuleNumber");
                _ModuleNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleNumber");
                OnModuleNumberChanged();
            }
        }
        private global::System.Int32 _ModuleNumber;
        partial void OnModuleNumberChanging(global::System.Int32 value);
        partial void OnModuleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleType
        {
            get
            {
                return _ModuleType;
            }
            set
            {
                OnModuleTypeChanging(value);
                ReportPropertyChanging("ModuleType");
                _ModuleType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleType");
                OnModuleTypeChanged();
            }
        }
        private global::System.Int32 _ModuleType;
        partial void OnModuleTypeChanging(global::System.Int32 value);
        partial void OnModuleTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PDIN
        {
            get
            {
                return _PDIN;
            }
            set
            {
                OnPDINChanging(value);
                ReportPropertyChanging("PDIN");
                _PDIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDIN");
                OnPDINChanged();
            }
        }
        private global::System.Int32 _PDIN;
        partial void OnPDINChanging(global::System.Int32 value);
        partial void OnPDINChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_Calibration_Ids", "Calibration")]
        public EntityCollection<Calibration> Calibrations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Calibration>("MonitoringModel.FK_Calibration_Ids", "Calibration");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Calibration>("MonitoringModel.FK_Calibration_Ids", "Calibration", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_HistoricalData_Ids", "HistoricalData")]
        public EntityCollection<HistoricalData> HistoricalDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HistoricalData>("MonitoringModel.FK_HistoricalData_Ids", "HistoricalData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HistoricalData>("MonitoringModel.FK_HistoricalData_Ids", "HistoricalData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_ReadIntervals_Ids", "ReadIntervals")]
        public EntityCollection<ReadInterval> ReadIntervals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReadInterval>("MonitoringModel.FK_ReadIntervals_Ids", "ReadIntervals");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReadInterval>("MonitoringModel.FK_ReadIntervals_Ids", "ReadIntervals", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MonitoringModel", Name="ReadInterval")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReadInterval : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReadInterval object.
        /// </summary>
        /// <param name="intervalId">Initial value of the IntervalId property.</param>
        /// <param name="idId">Initial value of the IdId property.</param>
        /// <param name="interval">Initial value of the Interval property.</param>
        /// <param name="maxInterval">Initial value of the MaxInterval property.</param>
        /// <param name="isEnabled">Initial value of the IsEnabled property.</param>
        public static ReadInterval CreateReadInterval(global::System.Int32 intervalId, global::System.Int32 idId, global::System.Int32 interval, global::System.Int32 maxInterval, global::System.Boolean isEnabled)
        {
            ReadInterval readInterval = new ReadInterval();
            readInterval.IntervalId = intervalId;
            readInterval.IdId = idId;
            readInterval.Interval = interval;
            readInterval.MaxInterval = maxInterval;
            readInterval.IsEnabled = isEnabled;
            return readInterval;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IntervalId
        {
            get
            {
                return _IntervalId;
            }
            set
            {
                if (_IntervalId != value)
                {
                    OnIntervalIdChanging(value);
                    ReportPropertyChanging("IntervalId");
                    _IntervalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IntervalId");
                    OnIntervalIdChanged();
                }
            }
        }
        private global::System.Int32 _IntervalId;
        partial void OnIntervalIdChanging(global::System.Int32 value);
        partial void OnIntervalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdId
        {
            get
            {
                return _IdId;
            }
            set
            {
                OnIdIdChanging(value);
                ReportPropertyChanging("IdId");
                _IdId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdId");
                OnIdIdChanged();
            }
        }
        private global::System.Int32 _IdId;
        partial void OnIdIdChanging(global::System.Int32 value);
        partial void OnIdIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Interval
        {
            get
            {
                return _Interval;
            }
            set
            {
                OnIntervalChanging(value);
                ReportPropertyChanging("Interval");
                _Interval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Interval");
                OnIntervalChanged();
            }
        }
        private global::System.Int32 _Interval;
        partial void OnIntervalChanging(global::System.Int32 value);
        partial void OnIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxInterval
        {
            get
            {
                return _MaxInterval;
            }
            set
            {
                OnMaxIntervalChanging(value);
                ReportPropertyChanging("MaxInterval");
                _MaxInterval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxInterval");
                OnMaxIntervalChanged();
            }
        }
        private global::System.Int32 _MaxInterval;
        partial void OnMaxIntervalChanging(global::System.Int32 value);
        partial void OnMaxIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEnabled
        {
            get
            {
                return _IsEnabled;
            }
            set
            {
                OnIsEnabledChanging(value);
                ReportPropertyChanging("IsEnabled");
                _IsEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEnabled");
                OnIsEnabledChanged();
            }
        }
        private global::System.Boolean _IsEnabled;
        partial void OnIsEnabledChanging(global::System.Boolean value);
        partial void OnIsEnabledChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MonitoringModel", "FK_ReadIntervals_Ids", "Ids")]
        public Id Id
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_ReadIntervals_Ids", "Ids").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_ReadIntervals_Ids", "Ids").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Id> IdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Id>("MonitoringModel.FK_ReadIntervals_Ids", "Ids");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Id>("MonitoringModel.FK_ReadIntervals_Ids", "Ids", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
